### ISSUE TITLE
Volume and Datapah plugin - what now?

### ISSUE THREAD

**Issue by rck** [xapi-project/xapi-storage-script#79]
Hi all,

I work for LINBIT, the company that maintains DRDB, and I'm currently working on integrating our SDS into XEN.

I want to mention that your plugin [documentation](https://xapi-project.github.io/xapi-storage/#introduction) is really great! I implemented both, a volume and a datapath plugin and both work on the command line. But now I'm a bit lost on how to further integrate these scripts.

I did put the `plugin.py` and `datapath.py` to `/usr/libexec/xapi-storage-script/datapath/linstor`. The necessary symlinks for `Datapath.attach`, `Datapath.activate`, `Datapath.deactivate`, `Datapath.detach`, and `Plugin.Query` are created.

The volume plugin got installed to `/usr/libexec/xapi-storage-script/volume/linstor`, symlinks for `Volume.clone` `Volume.create`, `Volume.destroy`, `Volume.resize`, `Volume.set`, `Volume.set_description`, `Volume.set_name`, `Volume.snapshot`, `Volume.stat`, `Volume.unset` got created.

When I execute `xapi-storage-script` writes `Registered datapath plugin linstor`. So far so good I guess, even though it does not mention something about the volume plugin.

Then I thought I probably need a SR plugin as well and modified the `DummySR.py` from `/opt/xensource/sm`, and enabled `linstor`, which is the type, in `/etc/xapi.conf/` (`sm-plugins`), and did a `xe-toolstack-restart`.

With that I can create a SR of type linstor, create a VDI, and a VDB. But that code never hits the storage-scripts. The only calls I get are in the SR (LINSTORSR.py) in the `vdi`-method.

And now I'm pretty confused :).
Is it possible to write the SR part as storage script? Or should I do it like I did by putting one to `/opt/xensource/sm`? How are they supposed to interact? Do I need to call my storage scripts from the SR's `vdi()` method? I hoped that I register a SR with a certain type, and that then "the XEN framework" would use datapath/volume plugins of the matching type.

Any help would be appreciated. As this is going to be FLOSS anyways, I can also put it in a public git repo now. I thought I ask first, for you it might be obvious what I'm doing wrong here.

**Comment by gaborigloi** [comment]
Hi @rck,

`/opt/xensource/sm` and `/etc/xapi.conf/` do not need to be modified, I think it should be sufficient to just implement a datapath and volume plugin :)

There are two things to watch out for.

1. Probably our [plugin documentation](https://xapi-project.github.io/xapi-storage/#plugin) should make it clearer, but when it says:
> The xapi toolstack expects all plugins to support a basic query interface.

That means that _both_ the datapath and the volume plugins have to implement this plugin interface.
That means that you need the `Plugin.query` symlink for the volume plugin too.
Also make sure you report `required_api_version` as the latest API version, which is currently 5.0: https://github.com/xapi-project/xapi-storage-script/blob/master/main.ml#L109

2. The volume plugin directory name should be `/usr/libexec/xapi-storage-script/volume/org.xen.xapi.storage.my_sr_type`. Then you'll be able to create SRs of type `my_sr_type`.

There should also be a xapi-storage-script log line for the volume plugin, something like `Adding org.xen.xapi.storage.my_sr_type`, which is logged from this line: https://github.com/xapi-project/xapi-storage-script/blob/master/main.ml#L1196

I think if you do these two fixes, it should work fine. Good luck!

**Comment by rck** [comment]
Hi @gaborigloi,

thank you for your help. The volume plugin is now detected and I also created a SR.py + symlinks. I can now create a SR with my type.

I guess switching to API 5.0 is currently  not possible, as initially this also has to work for XEN 7.1 LTSR. So I have to stay at API 3.0, right?

I will add a mini-patch documenting that **both** plugins require the query and then close this issue via a PR.

Thanks again, rck

**Comment by gaborigloi** [comment]
Thanks for your help @rck , the documentation actually lives in a different repo: https://github.com/xapi-project/xapi-storage/blob/master/generator/lib/plugin.ml#L90

As for the API versions, API 3.0 is quite different from the latest API. I think XenServer 7.1 LTSR uses this version of the SMAPIv3 interface: https://github.com/xapi-project/xapi-storage/tree/v0.9.0 . Only the latest API is documented online. So maybe it's best to write separate plugins for the LTSR and latest versions. Currently we still support 3.0 to some extent on the latest XenServer releases, but there might be some issues and we might drop it in the future.

**Comment by gaborigloi** [comment]
@rck I've discovered that we still have the docs for the old SMAPIv3 API version in git history: https://github.com/xapi-project/xapi-storage/tree/a64d4dcc310a10254ea1a4c5f44dc490bb3be322 , I think this one corresponds to v0.9.0 - you can browse the docs by opening the `index.html` file.

**Comment by edwintorok** [comment]
Note that backwards compatibility only exists for a limited number of volume APIs between SMAPI 3.0 and 5.0, see here for full list: https://github.com/xapi-project/xapi-storage-script/blob/master/test/volume/org.xen.xapi.storage.dummy/sr.py
SMAPIv3 version 3.0 in the LTSR was an experimental feature, and only tested with 1 plugin that used the APIs from the list above. The first released and supported version of SMAPIv3 was 5.0 in Lima.

I would recommend you develop your SR for Lima and SMAPIv3 5.0 first, and once that works see if it is possible to backport it to 3.0 for the LTSR.

**Comment by rck** [comment]
Hi guys,

thanks for your answers, these are very valuable hints!

> SMAPIv3 version 3.0 in the LTSR was an experimental feature, and only tested with 1 plugin that used the APIs from the list above. The first released and supported version of SMAPIv3 was 5.0 in Lima.

Just to make sure I got that right: 3.0 was never supported and more or less experimental until Lima (which should be XenServer 7.6, 2018) jumped to 5.0?

> I would recommend you develop your SR for Lima and SMAPIv3 5.0 first, and once that works see if it is possible to backport it to 3.0 for the LTSR.

And how about the data/volume plugins? I saw some changes in the API, but what do you think? Is it likely these work as expected on LTSR in production, or should one **really** try to avoid it and start with v5.0 on >= Lima?

**Comment by edwintorok** [comment]
> Hi guys,
> 
> thanks for your answers, these are very valuable hints!
> 
> > SMAPIv3 version 3.0 in the LTSR was an experimental feature, and only tested with 1 plugin that used the APIs from the list above. The first released and supported version of SMAPIv3 was 5.0 in Lima.
> 
> Just to make sure I got that right: 3.0 was never supported and more or less experimental until Lima (which should be XenServer 7.6, 2018) jumped to 5.0?

Correct.

> 
> > I would recommend you develop your SR for Lima and SMAPIv3 5.0 first, and once that works see if it is possible to backport it to 3.0 for the LTSR.
> 
> And how about the data/volume plugins? I saw some changes in the API, but what do you think? Is it likely these work as expected on LTSR in production, or should one **really** try to avoid it and start with v5.0 on >= Lima?

I think there were some backward incompatible changes on datapath plugins between 3.0 and 5.0, see for example: https://github.com/xapi-project/xapi-storage/commit/ccabfd74320d9e27e834f14d90c5876f4e151438#diff-29a24b3ae17fcf7330031ac063bd7a9c
If you use the 3.0 versions of this API then it might "just work" on the LTSR, but it is not something we test or support internally.
The next major version of the LTSR would include the 5.0 version of SMAPIv3 (since it is already in Lima), but I can't comment on when that becomes available.

**Comment by chandrikas** [comment]
Hi @rck , I would agree with @edwintorok. It might just work with version 3.0 of the API but since it was experimental, we haven't really worked on keeping the interfaces backward compatible. Do you have a special interest in making this work for the XS 7.1 LTSR?
