### ISSUE TITLE
Create sample datapath plugin that works with block devices

### ISSUE THREAD

**Issue by gaborigloi** [xapi-project/xapi-storage-script#84]

**Comment by rck** [comment]
Hi @gaborigloi 

Has there been any progress on that?

**Comment by gaborigloi** [comment]
Hi @rck,
It turns out that we already have an example datapath for block devices: https://github.com/xapi-project/xapi-storage-script/tree/master/examples/datapath/block
The interface it uses looks up to date (but I didn't study it in detail), but it's missing the `Datapath.open` and `Datapath.close` calls. I think these can be implemented as a no-op in this case.
Also, for a complete datapath plugin, the `Plugin.Query` script should also be implemented.
Hope this example code helps.

**Comment by gaborigloi** [comment]
Hi @rck , https://github.com/xapi-project/xapi-storage/pull/105 added an up to date, very simple datapath plugin that should be a good starting point
